import { SecondaryTask } from '../models/secondary-task.models';

export const SECONDARY_TASKS: SecondaryTask[] = [
  { id: 'fisico-1', text: 'Toma un vaso de agua', category: 'fisico', effort: 1, durationSec: 30, noveltyWeight: 5, antiSpamTag: 'agua-vaso' },
  { id: 'fisico-2', text: 'Estira cuello y hombros', category: 'fisico', effort: 1, durationSec: 40, noveltyWeight: 4, antiSpamTag: 'estira-cuello' },
  { id: 'fisico-3', text: 'Camina 2 minutos', category: 'fisico', effort: 2, durationSec: 120, noveltyWeight: 5, requiresDelay: true, cooldownMin: 90, antiSpamTag: 'camina-corta' },
  { id: 'fisico-4', text: 'Haz 10 sentadillas lentas', category: 'fisico', effort: 2, durationSec: 45, noveltyWeight: 4, requiresDelay: true, cooldownMin: 120, antiSpamTag: 'sentadillas-lentas' },
  { id: 'fisico-5', text: 'Respira de pie 45 segundos', category: 'fisico', effort: 1, durationSec: 45, noveltyWeight: 4, requiresDelay: true, cooldownMin: 45, antiSpamTag: 'respira-pie' },
  { id: 'fisico-6', text: 'Abre el pecho 30 segundos', category: 'fisico', effort: 1, durationSec: 30, noveltyWeight: 3, antiSpamTag: 'abre-pecho' },
  { id: 'fisico-7', text: 'Mueve tobillos 20 segundos', category: 'fisico', effort: 1, durationSec: 20, noveltyWeight: 3, antiSpamTag: 'mueve-tobillos' },
  { id: 'fisico-8', text: 'Sube y baja hombros', category: 'fisico', effort: 1, durationSec: 20, noveltyWeight: 3, antiSpamTag: 'hombros-suben' },
  { id: 'fisico-9', text: 'Toca tus puntas 20 segundos', category: 'fisico', effort: 2, durationSec: 20, noveltyWeight: 3, antiSpamTag: 'puntas-pies' },
  { id: 'fisico-10', text: 'Estira espalda 30 segundos', category: 'fisico', effort: 1, durationSec: 30, noveltyWeight: 4, requiresDelay: true, cooldownMin: 60, antiSpamTag: 'estira-espalda' },
  { id: 'fisico-11', text: 'Gira munecas 20 segundos', category: 'fisico', effort: 1, durationSec: 20, noveltyWeight: 2, antiSpamTag: 'gira-munecas' },
  { id: 'fisico-12', text: 'Sacude brazos 15 segundos', category: 'fisico', effort: 1, durationSec: 15, noveltyWeight: 2, antiSpamTag: 'sacude-brazos' },
  { id: 'fisico-13', text: 'Da 15 pasos lentos', category: 'fisico', effort: 1, durationSec: 25, noveltyWeight: 3, requiresDelay: true, cooldownMin: 45, antiSpamTag: 'pasos-lentos' },
  { id: 'fisico-14', text: 'Cambia tu postura ahora', category: 'fisico', effort: 1, durationSec: 10, noveltyWeight: 3, antiSpamTag: 'cambia-postura' },
  { id: 'fisico-15', text: 'Bebe agua despacio', category: 'fisico', effort: 1, durationSec: 35, noveltyWeight: 4, requiresDelay: true, cooldownMin: 45, antiSpamTag: 'agua-despacio' },
  { id: 'fisico-16', text: 'Mira lejos 30 segundos', category: 'fisico', effort: 1, durationSec: 30, noveltyWeight: 3, requiresDelay: true, cooldownMin: 45, antiSpamTag: 'mira-lejos' },
  { id: 'fisico-17', text: 'Eleva talones 15 veces', category: 'fisico', effort: 1, durationSec: 25, noveltyWeight: 3, antiSpamTag: 'eleva-talones' },
  { id: 'fisico-18', text: 'Inhala profundo 5 veces', category: 'fisico', effort: 1, durationSec: 25, noveltyWeight: 3, requiresDelay: true, cooldownMin: 40, antiSpamTag: 'inhala-cinco' },
  { id: 'fisico-19', text: 'Abre una ventana', category: 'fisico', effort: 1, durationSec: 15, noveltyWeight: 2, antiSpamTag: 'abre-ventana' },
  { id: 'fisico-20', text: 'Ponte de pie 1 minuto', category: 'fisico', effort: 1, durationSec: 60, noveltyWeight: 4, requiresDelay: true, cooldownMin: 60, antiSpamTag: 'pie-un-minuto' },

  { id: 'orden-1', text: 'Ordena 3 objetos cerca', category: 'orden', effort: 1, durationSec: 30, noveltyWeight: 5, antiSpamTag: 'ordena-tres' },
  { id: 'orden-2', text: 'Limpia tu escritorio', category: 'orden', effort: 2, durationSec: 90, noveltyWeight: 4, requiresDelay: true, cooldownMin: 120, antiSpamTag: 'limpia-escritorio' },
  { id: 'orden-3', text: 'Dobla una prenda', category: 'orden', effort: 1, durationSec: 25, noveltyWeight: 3, antiSpamTag: 'dobla-prenda' },
  { id: 'orden-4', text: 'Bota algo innecesario', category: 'orden', effort: 1, durationSec: 20, noveltyWeight: 4, antiSpamTag: 'bota-innecesario' },
  { id: 'orden-5', text: 'Guarda un cable suelto', category: 'orden', effort: 1, durationSec: 25, noveltyWeight: 3, antiSpamTag: 'guarda-cable' },
  { id: 'orden-6', text: 'Alinea lo que usas hoy', category: 'orden', effort: 1, durationSec: 35, noveltyWeight: 3, antiSpamTag: 'alinea-objetos' },
  { id: 'orden-7', text: 'Vacía una bolsa pequena', category: 'orden', effort: 2, durationSec: 60, noveltyWeight: 4, requiresDelay: true, cooldownMin: 90, antiSpamTag: 'vacia-bolsa' },
  { id: 'orden-8', text: 'Limpia la pantalla', category: 'orden', effort: 1, durationSec: 40, noveltyWeight: 3, antiSpamTag: 'limpia-pantalla' },
  { id: 'orden-9', text: 'Recoge papeles sueltos', category: 'orden', effort: 1, durationSec: 35, noveltyWeight: 3, antiSpamTag: 'recoge-papeles' },
  { id: 'orden-10', text: 'Cierra una pestana fisica', category: 'orden', effort: 1, durationSec: 10, noveltyWeight: 2, antiSpamTag: 'cierra-gaveta' },
  { id: 'orden-11', text: 'Lava una taza', category: 'orden', effort: 2, durationSec: 80, noveltyWeight: 4, requiresDelay: true, cooldownMin: 120, antiSpamTag: 'lava-taza' },
  { id: 'orden-12', text: 'Guarda algo fuera de lugar', category: 'orden', effort: 1, durationSec: 20, noveltyWeight: 3, antiSpamTag: 'guarda-fuera-lugar' },
  { id: 'orden-13', text: 'Sacude una superficie', category: 'orden', effort: 1, durationSec: 30, noveltyWeight: 2, antiSpamTag: 'sacude-superficie' },
  { id: 'orden-14', text: 'Haz espacio en una repisa', category: 'orden', effort: 2, durationSec: 70, noveltyWeight: 3, requiresDelay: true, cooldownMin: 90, antiSpamTag: 'espacio-repisa' },
  { id: 'orden-15', text: 'Endereza una silla', category: 'orden', effort: 1, durationSec: 10, noveltyWeight: 2, antiSpamTag: 'endereza-silla' },
  { id: 'orden-16', text: 'Ordena tus llaves', category: 'orden', effort: 1, durationSec: 20, noveltyWeight: 3, antiSpamTag: 'ordena-llaves' },
  { id: 'orden-17', text: 'Limpia una mancha pequena', category: 'orden', effort: 1, durationSec: 45, noveltyWeight: 3, requiresDelay: true, cooldownMin: 60, antiSpamTag: 'limpia-mancha' },
  { id: 'orden-18', text: 'Guarda un papel pendiente', category: 'orden', effort: 1, durationSec: 30, noveltyWeight: 3, antiSpamTag: 'guarda-papel' },
  { id: 'orden-19', text: 'Acomoda tus zapatos', category: 'orden', effort: 1, durationSec: 30, noveltyWeight: 2, antiSpamTag: 'acomoda-zapatos' },
  { id: 'orden-20', text: 'Despeja una esquina', category: 'orden', effort: 2, durationSec: 60, noveltyWeight: 4, requiresDelay: true, cooldownMin: 90, antiSpamTag: 'despeja-esquina' },

  { id: 'mental-1', text: 'Respira 60 segundos sin pantalla', category: 'mental', effort: 1, durationSec: 60, noveltyWeight: 5, requiresDelay: true, cooldownMin: 45, antiSpamTag: 'respira-sin-pantalla' },
  { id: 'mental-2', text: 'Mira por la ventana', category: 'mental', effort: 1, durationSec: 60, noveltyWeight: 4, requiresDelay: true, cooldownMin: 45, antiSpamTag: 'mira-ventana' },
  { id: 'mental-3', text: 'Haz pausa sin estimulo', category: 'mental', effort: 1, durationSec: 45, noveltyWeight: 4, requiresDelay: true, cooldownMin: 45, antiSpamTag: 'pausa-estimulo' },
  { id: 'mental-4', text: 'Escribe una frase simple', category: 'mental', effort: 1, durationSec: 35, noveltyWeight: 4, antiSpamTag: 'frase-simple' },
  { id: 'mental-5', text: 'Cuenta 10 respiraciones', category: 'mental', effort: 1, durationSec: 40, noveltyWeight: 3, requiresDelay: true, cooldownMin: 45, antiSpamTag: 'cuenta-respiraciones' },
  { id: 'mental-6', text: 'Observa un sonido cercano', category: 'mental', effort: 1, durationSec: 30, noveltyWeight: 3, antiSpamTag: 'sonido-cercano' },
  { id: 'mental-7', text: 'Nombra 3 cosas visibles', category: 'mental', effort: 1, durationSec: 20, noveltyWeight: 3, antiSpamTag: 'nombra-visibles' },
  { id: 'mental-8', text: 'Cierra los ojos 20 segundos', category: 'mental', effort: 1, durationSec: 20, noveltyWeight: 2, antiSpamTag: 'ojos-cerrados' },
  { id: 'mental-9', text: 'Describe tu entorno mentalmente', category: 'mental', effort: 1, durationSec: 30, noveltyWeight: 3, antiSpamTag: 'describe-entorno' },
  { id: 'mental-10', text: 'Haz una pausa quieta', category: 'mental', effort: 1, durationSec: 25, noveltyWeight: 3, requiresDelay: true, cooldownMin: 40, antiSpamTag: 'pausa-quieta' },
  { id: 'mental-11', text: 'Escribe una prioridad breve', category: 'mental', effort: 1, durationSec: 30, noveltyWeight: 4, antiSpamTag: 'prioridad-breve' },
  { id: 'mental-12', text: 'Recuerda algo pendiente', category: 'mental', effort: 1, durationSec: 15, noveltyWeight: 2, antiSpamTag: 'recuerda-pendiente' },
  { id: 'mental-13', text: 'Mira un punto fijo', category: 'mental', effort: 1, durationSec: 30, noveltyWeight: 2, requiresDelay: true, cooldownMin: 35, antiSpamTag: 'punto-fijo' },
  { id: 'mental-14', text: 'Inhala y exhala lento', category: 'mental', effort: 1, durationSec: 35, noveltyWeight: 3, requiresDelay: true, cooldownMin: 40, antiSpamTag: 'inhala-exhala-lento' },
  { id: 'mental-15', text: 'Anota una idea breve', category: 'mental', effort: 1, durationSec: 35, noveltyWeight: 3, antiSpamTag: 'idea-breve' },
  { id: 'mental-16', text: 'Suelta la mandibula 20 segundos', category: 'mental', effort: 1, durationSec: 20, noveltyWeight: 2, antiSpamTag: 'suelta-mandibula' },
  { id: 'mental-17', text: 'Repite una frase util', category: 'mental', effort: 1, durationSec: 20, noveltyWeight: 2, antiSpamTag: 'frase-util' },
  { id: 'mental-18', text: 'Haz silencio 1 minuto', category: 'mental', effort: 2, durationSec: 60, noveltyWeight: 4, requiresDelay: true, cooldownMin: 60, antiSpamTag: 'silencio-minuto' },
  { id: 'mental-19', text: 'Cuenta 20 segundos lento', category: 'mental', effort: 1, durationSec: 20, noveltyWeight: 2, antiSpamTag: 'cuenta-lento' },
  { id: 'mental-20', text: 'Escribe una palabra clave', category: 'mental', effort: 1, durationSec: 20, noveltyWeight: 2, antiSpamTag: 'palabra-clave' },

  { id: 'social-1', text: 'Responde un mensaje pendiente', category: 'social', effort: 1, durationSec: 45, noveltyWeight: 5, antiSpamTag: 'responde-mensaje' },
  { id: 'social-2', text: 'Saluda con intencion', category: 'social', effort: 1, durationSec: 15, noveltyWeight: 3, antiSpamTag: 'saluda-intencion' },
  { id: 'social-3', text: 'Agradece algo a alguien', category: 'social', effort: 1, durationSec: 30, noveltyWeight: 4, antiSpamTag: 'agradece-algo' },
  { id: 'social-4', text: 'Pregunta como va su dia', category: 'social', effort: 1, durationSec: 25, noveltyWeight: 4, antiSpamTag: 'pregunta-dia' },
  { id: 'social-5', text: 'Envia un audio breve', category: 'social', effort: 2, durationSec: 45, noveltyWeight: 3, requiresDelay: true, cooldownMin: 120, antiSpamTag: 'audio-breve' },
  { id: 'social-6', text: 'Confirma un plan pendiente', category: 'social', effort: 1, durationSec: 35, noveltyWeight: 4, antiSpamTag: 'confirma-plan' },
  { id: 'social-7', text: 'Responde con claridad', category: 'social', effort: 1, durationSec: 25, noveltyWeight: 3, antiSpamTag: 'responde-claro' },
  { id: 'social-8', text: 'Manda un gracias corto', category: 'social', effort: 1, durationSec: 20, noveltyWeight: 3, antiSpamTag: 'gracias-corto' },
  { id: 'social-9', text: 'Haz una pregunta concreta', category: 'social', effort: 1, durationSec: 20, noveltyWeight: 3, antiSpamTag: 'pregunta-concreta' },
  { id: 'social-10', text: 'Invita a caminar luego', category: 'social', effort: 2, durationSec: 40, noveltyWeight: 4, antiSpamTag: 'invita-caminar' },
  { id: 'social-11', text: 'Escribe un mensaje directo', category: 'social', effort: 1, durationSec: 30, noveltyWeight: 3, antiSpamTag: 'mensaje-directo' },
  { id: 'social-12', text: 'Avisa que llegaste bien', category: 'social', effort: 1, durationSec: 15, noveltyWeight: 2, antiSpamTag: 'avisa-llegada' },
  { id: 'social-13', text: 'Felicita algo especifico', category: 'social', effort: 1, durationSec: 25, noveltyWeight: 3, antiSpamTag: 'felicita-especifico' },
  { id: 'social-14', text: 'Pregunta por un detalle', category: 'social', effort: 1, durationSec: 20, noveltyWeight: 3, antiSpamTag: 'pregunta-detalle' },
  { id: 'social-15', text: 'Recupera un contacto corto', category: 'social', effort: 2, durationSec: 40, noveltyWeight: 4, antiSpamTag: 'recupera-contacto' },
  { id: 'social-16', text: 'Saluda sin mirar pantalla', category: 'social', effort: 1, durationSec: 10, noveltyWeight: 2, antiSpamTag: 'saluda-sin-pantalla' },
  { id: 'social-17', text: 'Agradece algo en persona', category: 'social', effort: 1, durationSec: 15, noveltyWeight: 3, antiSpamTag: 'agradece-persona' },
  { id: 'social-18', text: 'Haz seguimiento a alguien', category: 'social', effort: 1, durationSec: 30, noveltyWeight: 4, antiSpamTag: 'seguimiento-alguien' },
  { id: 'social-19', text: 'Comparte una idea util', category: 'social', effort: 1, durationSec: 25, noveltyWeight: 3, antiSpamTag: 'comparte-idea' },
  { id: 'social-20', text: 'Confirma una hora exacta', category: 'social', effort: 1, durationSec: 20, noveltyWeight: 2, antiSpamTag: 'confirma-hora' }
];
